const C = {};
C.Width = 1000 ;
C.Height = 600 ;
C.goalH = 100 ;
C.goalW = 50 ;
C.xgap = C.Width / 40 ;
C.ygap = C.Height / 20;
C.backgroundColor = (4, 199, 75) ; // maybe unused
C.playerRadius = 12 ;
C.ballBigRadius = 15;
C.ballRadius = 10 ;
C.shootSpeed = 9;
C.playerAcc = 0.3 ;
C.picWidth = 48 ;
C.picHeight = 48 ;
C.animationSpeed = 0.04 ; // it is ratio by which vel is multiplied
if(typeof module != "undefined"){
    global.C = C;
}